spring:
  datasource:
    url: jdbc:mysql://####:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&autoReconnect=true&failOverReadOnly=false
    username: ####
    password: ####
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapperxml/*Mapper.xml # mapper接口对应xml文件所在包位置
