spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    call-setters-on-nulls: true # 不忽略查询结果为null的字段
  mapper-locations: classpath:mapperxml/*Mapper.xml # mapper接口对应xml文件所在包位置
